Repository Mike-Mortensen-Portfolio/PubHub_H6_Final, pull requests merged in 2024-03, with the labels that each got.

#52 Identity and EF Core
  PubHub/PubHub.API/Domain/Entities/AccountType.cs
  PubHub/PubHub.API/Domain/Entities/Author.cs
  PubHub/PubHub.API/Domain/Entities/Book.cs
  PubHub/PubHub.API/Domain/Entities/ContentType.cs
  PubHub/PubHub.API/Domain/Entities/Genre.cs
  PubHub/PubHub.API/Domain/Entities/Operator.cs
  PubHub/PubHub.API/Domain/Entities/Publisher.cs
  PubHub/PubHub.API/Domain/Entities/User.cs
  PubHub/PubHub.API/Domain/Extensions/EntityTypeBuilderExtensions.cs
  PubHub/PubHub.API/Domain/Identity/Account.cs
  PubHub/PubHub.API/Domain/PubHubContext.cs
  PubHub/PubHub.API/Domain/Seeding/AccountTypeSeed.cs
  PubHub/PubHub.API/Domain/Seeding/ContentTypeSeed.cs
  PubHub/PubHub.API/Domain/Seeding/GenreSeed.cs
  PubHub/PubHub.API/Program.cs
  PubHub/PubHub.API/PubHub.API.csproj
  PubHub/PubHub.API/ServiceExtensions.cs
  PubHub/PubHub.API/appsettings.json
Labels: setup

#62 User controller
  PubHub/PubHub.API/Controllers/UserController.cs
  PubHub/PubHub.API/Domain/Entities/Book.cs
  PubHub/PubHub.API/Domain/Entities/User.cs
  PubHub/PubHub.API/Domain/Identity/Account.cs
  PubHub/PubHub.API/Domain/PubHubContext.cs
  PubHub/PubHub.API/PubHub.API.csproj
  PubHub/PubHub.Common/AccountTypeConstants.cs
  PubHub/PubHub.Common/Models/AccountCreateModel.cs
  PubHub/PubHub.Common/Models/AccountUpdateModel.cs
  PubHub/PubHub.Common/Models/BookInfoModel.cs
  PubHub/PubHub.Common/Models/UserCreateModel.cs
  PubHub/PubHub.Common/Models/UserInfoModel.cs
  PubHub/PubHub.Common/Models/UserUpdateModel.cs
  PubHub/PubHub.Common/PubHub.Common.csproj
  PubHub/PubHub.sln
Labels: feature

#74 Removing semicolon in Operator entity.
  PubHub/PubHub.API/Domain/Entities/Operator.cs
Labels: bug

#75 Publisher controller
  .editorconfig
  PubHub/PubHub.API/Controllers/PublishersController.cs
  PubHub/PubHub.API/Controllers/UserController.cs
  PubHub/PubHub.API/Controllers/WeatherForecastController.cs
  PubHub/PubHub.API/WeatherForecast.cs
  PubHub/PubHub.Common/Models/PublisherCreateModel.cs
  PubHub/PubHub.Common/Models/PublisherInfoModel.cs
  PubHub/PubHub.Common/Models/PublisherListModel.cs
  PubHub/PubHub.Common/Models/PublisherUpdateModel.cs
Labels: feature

#78 Implemented ServiceExtension and UserService
  PubHub/PubHub.AdminPortal/Program.cs
  PubHub/PubHub.AdminPortal/PubHub.AdminPortal.csproj
  PubHub/PubHub.AdminPortal/appsettings.json
  PubHub/PubHub.Common/ApiService/ApiConstants.cs
  PubHub/PubHub.Common/ApiService/ApiOptions.cs
  PubHub/PubHub.Common/ApiService/PubHubApiService.cs
  PubHub/PubHub.Common/ApiService/ServiceRoot.cs
  PubHub/PubHub.Common/Extensions/ServiceExtensions.cs
  PubHub/PubHub.Common/PubHub.Common.csproj
  PubHub/PubHub.Common/Services/ErrorResponse.cs
  PubHub/PubHub.Common/Services/ServiceInstanceResult.cs
  PubHub/PubHub.Common/Services/ServiceResult.cs
  PubHub/PubHub.Common/Services/UserService.cs
Labels: feature

#83 Added Book Controller
  PubHub/PubHub.API/Controllers/BooksController.cs
  PubHub/PubHub.API/Controllers/Problems/BadRequestSpecification.cs
  PubHub/PubHub.API/Controllers/Problems/DuplicateProblemSpecification.cs
  PubHub/PubHub.API/Controllers/Problems/InternalServerErrorSpecification.cs
  PubHub/PubHub.API/Controllers/Problems/NotFoundSpecification.cs
  PubHub/PubHub.API/Controllers/Problems/UnprocessableEntitySpecification.cs
  PubHub/PubHub.API/Controllers/PublishersController.cs
  PubHub/PubHub.API/Controllers/UserController.cs
  PubHub/PubHub.API/Controllers/UsersController.cs
  PubHub/PubHub.API/Domain/Extensions/BookExtensions.cs
  PubHub/PubHub.API/Domain/Extensions/IQueryableExtensions.cs
  PubHub/PubHub.API/Domain/PubHubContext.cs
  PubHub/PubHub.API/Domain/Seeding/BookSeed.cs
  PubHub/PubHub.API/EndpointTests/Books.http
  PubHub/PubHub.API/EndpointTests/PubHub.API.http
  PubHub/PubHub.API/Migrations/20240328151432_Seeding.Designer.cs
  PubHub/PubHub.API/Migrations/20240328151432_Seeding.cs
  PubHub/PubHub.API/Migrations/PubHubContextModelSnapshot.cs
  PubHub/PubHub.API/PubHub.API.csproj
  PubHub/PubHub.API/PubHub.API.http
  PubHub/PubHub.API/ServiceExtensions.cs
  PubHub/PubHub.Common/ContentTypeConstants.cs
  PubHub/PubHub.Common/IntegrityConstants.cs
  PubHub/PubHub.Common/Models/Accounts/AccountCreateModel.cs
  PubHub/PubHub.Common/Models/Accounts/AccountUpdateModel.cs
  PubHub/PubHub.Common/Models/BookInfoModel.cs
  PubHub/PubHub.Common/Models/Books/AuthorInfoModel.cs
  PubHub/PubHub.Common/Models/Books/BookCreateModel.cs
  PubHub/PubHub.Common/Models/Books/BookInfoModel.cs
  PubHub/PubHub.Common/Models/Books/BookPublisherModel.cs
  PubHub/PubHub.Common/Models/Books/BookQuery.cs
  PubHub/PubHub.Common/Models/Books/BookUpdateModel.cs
  PubHub/PubHub.Common/Models/Books/ContentTypeInfoModel.cs
  PubHub/PubHub.Common/Models/Books/GenreInfoModel.cs
  PubHub/PubHub.Common/Models/Books/OrderBooksBy.cs
  PubHub/PubHub.Common/Models/PaginationQuery.cs
  PubHub/PubHub.Common/Models/Publishers/PublisherCreateModel.cs
  PubHub/PubHub.Common/Models/Publishers/PublisherInfoModel.cs
  PubHub/PubHub.Common/Models/Publishers/PublisherListModel.cs
  PubHub/PubHub.Common/Models/Publishers/PublisherUpdateModel.cs
  PubHub/PubHub.Common/Models/SearchQuery.cs
  PubHub/PubHub.Common/Models/Users/UserCreateModel.cs
  PubHub/PubHub.Common/Models/Users/UserInfoModel.cs
  PubHub/PubHub.Common/Models/Users/UserUpdateModel.cs
  PubHub/PubHub.sln
Labels: feature

#85 BookService have been added to call against the BookController endpoints
  PubHub/PubHub.Common/ApiService/PubHubApiService.cs
  PubHub/PubHub.Common/Extensions/ServiceExtensions.cs
  PubHub/PubHub.Common/Services/BookService.cs
  PubHub/PubHub.Common/Services/IBookService.cs
  PubHub/PubHub.Common/Services/IUserService.cs
  PubHub/PubHub.Common/Services/UserService.cs
Labels: feature

#86 Added search functionality to PublishersController
  PubHub/PubHub.API/Controllers/BooksController.cs
  PubHub/PubHub.API/Controllers/PublishersController.cs
  PubHub/PubHub.API/Controllers/UsersController.cs
  PubHub/PubHub.API/Domain/Extensions/PublisherExtensions.cs
  PubHub/PubHub.Common/Models/Publishers/OrderPublisherBy.cs
  PubHub/PubHub.Common/Models/Publishers/PublisherQuery.cs
  PubHub/PubHub.Common/Services/ErrorResponse.cs
  PubHub/PubHub.Common/Services/UserService.cs
Labels: feature

#88 PublisherService has been added
  PubHub/PubHub.Common/Extensions/ServiceExtensions.cs
  PubHub/PubHub.Common/Services/BookService.cs
  PubHub/PubHub.Common/Services/IBookService.cs
  PubHub/PubHub.Common/Services/IPublisherService.cs
  PubHub/PubHub.Common/Services/IUserService.cs
  PubHub/PubHub.Common/Services/PublisherService.cs
  PubHub/PubHub.Common/Services/UserService.cs
Labels: feature

#89 Msm/rfc9457 specifications
  PubHub/PubHub.API/Controllers/BooksController.cs
  PubHub/PubHub.API/Controllers/Problems/DuplicateProblemSpecification.cs
  PubHub/PubHub.API/Controllers/PublishersController.cs
  PubHub/PubHub.API/Controllers/UsersController.cs
Labels: feature
