Repository Mike-Mortensen-Portfolio/PubHub_H6_Final, pull requests merged in 2024-04, with the labels that each got.

#87 EF Core configuration
  .editorconfig
  PubHub/PubHub.API/Controllers/BooksController.cs
  PubHub/PubHub.API/Controllers/PublishersController.cs
  PubHub/PubHub.API/Controllers/UsersController.cs
  PubHub/PubHub.API/Domain/Entities/AccessType.cs
  PubHub/PubHub.API/Domain/Entities/AccountType.cs
  PubHub/PubHub.API/Domain/Entities/Author.cs
  PubHub/PubHub.API/Domain/Entities/Book.cs
  PubHub/PubHub.API/Domain/Entities/BookAuthor.cs
  PubHub/PubHub.API/Domain/Entities/BookGenre.cs
  PubHub/PubHub.API/Domain/Entities/ContentType.cs
  PubHub/PubHub.API/Domain/Entities/Genre.cs
  PubHub/PubHub.API/Domain/Entities/Operator.cs
  PubHub/PubHub.API/Domain/Entities/Publisher.cs
  PubHub/PubHub.API/Domain/Entities/User.cs
  PubHub/PubHub.API/Domain/Entities/UserBook.cs
  PubHub/PubHub.API/Domain/Extensions/EntityTypeBuilderExtensions.cs
  PubHub/PubHub.API/Domain/Identity/Account.cs
  PubHub/PubHub.API/Domain/PubHubContext.cs
  PubHub/PubHub.API/Domain/Seeding/AccessTypeSeed.cs
  PubHub/PubHub.API/Domain/Seeding/AccountSeed.cs
  PubHub/PubHub.API/Domain/Seeding/AccountTypeSeed.cs
  PubHub/PubHub.API/Domain/Seeding/AuthorSeed.cs
  PubHub/PubHub.API/Domain/Seeding/BookSeed.cs
  PubHub/PubHub.API/Domain/Seeding/ContentTypeSeed.cs
  PubHub/PubHub.API/Domain/Seeding/GenreSeed.cs
  PubHub/PubHub.API/Domain/Seeding/OperatorSeed.cs
  PubHub/PubHub.API/Domain/Seeding/PublisherSeed.cs
  PubHub/PubHub.API/Domain/Seeding/UserSeed.cs
  PubHub/PubHub.API/Domain/UUID/UuidValueGenerator.cs
  PubHub/PubHub.API/Migrations/20240328151432_Seeding.cs
  PubHub/PubHub.API/Migrations/20240329153643_Initial.Designer.cs
  PubHub/PubHub.API/Migrations/20240329153643_Initial.cs
  PubHub/PubHub.API/Migrations/20240330101825_Seeding.Designer.cs
  PubHub/PubHub.API/Migrations/20240330101825_Seeding.cs
  PubHub/PubHub.API/Migrations/PubHubContextModelSnapshot.cs
  PubHub/PubHub.API/PubHub.API.csproj
  PubHub/PubHub.API/ServiceExtensions.cs
  PubHub/PubHub.Common/IntegrityConstants.cs
  PubHub/PubHub.Common/Models/Books/AuthorInfoModel.cs
  PubHub/PubHub.Common/Models/Books/BookCreateModel.cs
  PubHub/PubHub.Common/Models/Books/BookInfoModel.cs
  PubHub/PubHub.Common/Models/Books/BookPublisherModel.cs
  PubHub/PubHub.Common/Models/Books/BookQuery.cs
  PubHub/PubHub.Common/Models/Books/BookUpdateModel.cs
  PubHub/PubHub.Common/Models/Books/ContentTypeInfoModel.cs
  PubHub/PubHub.Common/Models/Books/GenreInfoModel.cs
  PubHub/PubHub.Common/Models/Publishers/PublisherInfoModel.cs
  PubHub/PubHub.Common/Models/Publishers/PublisherListModel.cs
  PubHub/PubHub.Common/Models/Users/UserInfoModel.cs
Labels: feature

#110 Added author controller
  PubHub/PubHub.API/Controllers/AuthorsController.cs
  PubHub/PubHub.API/Controllers/BooksController.cs
  PubHub/PubHub.API/Controllers/PublishersController.cs
  PubHub/PubHub.API/Controllers/UsersController.cs
  PubHub/PubHub.Common/IntegrityConstants.cs
  PubHub/PubHub.Common/Models/Authors/AuthorCreateModel.cs
  PubHub/PubHub.Common/Models/Authors/AuthorInfoModel.cs
  PubHub/PubHub.Common/Models/Books/BookInfoModel.cs
Labels: feature

#114 Author services added
  PubHub/PubHub.API/Controllers/AuthorsController.cs
  PubHub/PubHub.Common/Extensions/ServiceExtensions.cs
  PubHub/PubHub.Common/Services/AuthorService.cs
  PubHub/PubHub.Common/Services/BookService.cs
  PubHub/PubHub.Common/Services/IAuthorService.cs
Labels: feature

#116 Change return types on Empty lists.
  PubHub/PubHub.Common/Services/AuthorService.cs
  PubHub/PubHub.Common/Services/BookService.cs
  PubHub/PubHub.Common/Services/PublisherService.cs
  PubHub/PubHub.Common/Services/UserService.cs
Labels: feature

#117 Add AuthController
  .editorconfig
  PubHub/PubHub.API/Controllers/AuthController.cs
  PubHub/PubHub.API/Controllers/BooksController.cs
  PubHub/PubHub.API/Controllers/Problems/UnauthorizedSpecification.cs
  PubHub/PubHub.API/Domain/Auth/AuthOptions.cs
  PubHub/PubHub.API/Domain/Auth/AuthService.cs
  PubHub/PubHub.API/Domain/Auth/TokenResult.cs
  PubHub/PubHub.API/Domain/Identity/Account.cs
  PubHub/PubHub.API/Domain/Identity/AccountRefreshToken.cs
  PubHub/PubHub.API/Domain/PubHubContext.cs
  PubHub/PubHub.API/Migrations/20240330101825_Seeding.cs
  PubHub/PubHub.API/Migrations/20240402175252_Initial.Designer.cs
  PubHub/PubHub.API/Migrations/20240402175252_Initial.cs
  PubHub/PubHub.API/Migrations/20240402175319_Seeding.Designer.cs
  PubHub/PubHub.API/Migrations/20240402175319_Seeding.cs
  PubHub/PubHub.API/Migrations/PubHubContextModelSnapshot.cs
  PubHub/PubHub.API/Program.cs
  PubHub/PubHub.API/ServiceExtensions.cs
  PubHub/PubHub.API/appsettings.json
  PubHub/PubHub.Common/Models/Accounts/TokenResponseModel.cs
  PubHub/PubHub.Common/PubHub.Common.csproj
Labels: feature

#119 Added ContentType controller
  PubHub/PubHub.API/Controllers/BooksController.cs
  PubHub/PubHub.API/Controllers/ContentTypeController.cs
  PubHub/PubHub.API/Controllers/PublishersController.cs
  PubHub/PubHub.API/Controllers/UsersController.cs
  PubHub/PubHub.Common/Models/Books/BookInfoModel.cs
  PubHub/PubHub.Common/Models/ContentTypes/ContentTypeInfoModel.cs
Labels: feature

#120 ContentTypeService added
  PubHub/PubHub.Common/Extensions/ServiceExtensions.cs
  PubHub/PubHub.Common/Services/ContentTypeService.cs
  PubHub/PubHub.Common/Services/IContentTypeService.cs
Labels: feature

#126 Jbn/auth service
  PubHub/PubHub.Common/Extensions/ServiceExtensions.cs
  PubHub/PubHub.Common/Models/Authentication/LoginInfo.cs
  PubHub/PubHub.Common/Models/Authentication/TokenInfo.cs
  PubHub/PubHub.Common/Services/AuthenticationService.cs
  PubHub/PubHub.Common/Services/IAuthenticationService.cs
Labels: feature

#129 Add Serilog to API project
  PubHub/PubHub.API/Controllers/AuthController.cs
  PubHub/PubHub.API/Controllers/AuthorsController.cs
  PubHub/PubHub.API/Controllers/BooksController.cs
  PubHub/PubHub.API/Controllers/GenresController.cs
  PubHub/PubHub.API/Controllers/PublishersController.cs
  PubHub/PubHub.API/Controllers/UsersController.cs
  PubHub/PubHub.API/Domain/Auth/AuthService.cs
  PubHub/PubHub.API/Program.cs
  PubHub/PubHub.API/PubHub.API.csproj
  PubHub/PubHub.API/ServiceExtensions.cs
  PubHub/PubHub.API/WebApplicationBuilderExtensions.cs
Labels: feature

#130 HttpClientService with Polly
  PubHub/PubHub.AdminPortal/Program.cs
  PubHub/PubHub.BookMobile/MauiProgram.cs
  PubHub/PubHub.BookMobile/PubHub.BookMobile.csproj
  PubHub/PubHub.BookWeb/Program.cs
  PubHub/PubHub.BookWeb/PubHub.BookWeb.csproj
  PubHub/PubHub.Common/ApiService/ApiConstants.cs
  PubHub/PubHub.Common/ApiService/ApiOptions.cs
  PubHub/PubHub.Common/ApiService/ServiceRoot.cs
  PubHub/PubHub.Common/Extensions/ServiceExtensions.cs
  PubHub/PubHub.Common/PubHub.Common.csproj
  PubHub/PubHub.Common/Services/AuthenticationService.cs
  PubHub/PubHub.Common/Services/AuthorService.cs
  PubHub/PubHub.Common/Services/BookService.cs
  PubHub/PubHub.Common/Services/ContentTypeService.cs
  PubHub/PubHub.Common/Services/GenreService.cs
  PubHub/PubHub.Common/Services/HttpClientService.cs
  PubHub/PubHub.Common/Services/IBookService.cs
  PubHub/PubHub.Common/Services/IHttpClientService.cs
  PubHub/PubHub.Common/Services/PublisherService.cs
  PubHub/PubHub.Common/Services/UserService.cs
Labels: feature

#131 Manage book functionality
  PubHub/PubHub.AdminPortal/Components/App.razor
  PubHub/PubHub.AdminPortal/Components/Helpers/FileHandler.cs
  PubHub/PubHub.AdminPortal/Components/Layout/MainLayout.razor
  PubHub/PubHub.AdminPortal/Components/Models/BookForm.cs
  PubHub/PubHub.AdminPortal/Components/Models/ResponseCodeConstants.cs
  PubHub/PubHub.AdminPortal/Components/Models/TestData.cs
  PubHub/PubHub.AdminPortal/Components/Pages/Books.razor
  PubHub/PubHub.AdminPortal/Components/Pages/Modals/Book/CreateBookModal.razor
  PubHub/PubHub.AdminPortal/Components/Pages/Modals/Book/RemoveBookModal.razor
  PubHub/PubHub.AdminPortal/Components/Pages/Modals/Book/UpdateBookModal.razor
  PubHub/PubHub.AdminPortal/Components/Pages/Operator/ManageFrontPage.razor
  PubHub/PubHub.AdminPortal/Components/Pages/Operator/ManagePublishers.razor
  PubHub/PubHub.AdminPortal/Components/Pages/Publisher/BookStatistics.razor
  PubHub/PubHub.AdminPortal/Components/Pages/Publisher/Books.razor
  PubHub/PubHub.AdminPortal/Components/Pages/Shared/AuthorInputSelect.razor
  PubHub/PubHub.AdminPortal/Components/_Imports.razor
  PubHub/PubHub.AdminPortal/Program.cs
  PubHub/PubHub.AdminPortal/PubHub.AdminPortal.csproj
  PubHub/PubHub.AdminPortal/appsettings.json
  PubHub/PubHub.AdminPortal/wwwroot/app.css
  PubHub/PubHub.Common/Services/AuthorService.cs
  PubHub/PubHub.Common/Services/BookService.cs
  PubHub/PubHub.Common/Services/ContentTypeService.cs
  PubHub/PubHub.Common/Services/GenreService.cs
  PubHub/PubHub.Common/Services/IAuthorService.cs
  PubHub/PubHub.Common/Services/IBookService.cs
  PubHub/PubHub.Common/Services/IContentTypeService.cs
  PubHub/PubHub.Common/Services/IGenreService.cs
  PubHub/PubHub.Common/Services/IPublisherService.cs
  PubHub/PubHub.Common/Services/IUserService.cs
  PubHub/PubHub.Common/Services/PublisherService.cs
  PubHub/PubHub.Common/Services/ServiceInstanceResult.cs
  PubHub/PubHub.Common/Services/ServiceResult.cs
  PubHub/PubHub.Common/Services/UserService.cs
  PubHub/PubHub.sln
Labels: feature

#134 Register accounts
  PubHub/PubHub.API/Controllers/AuthController.cs
  PubHub/PubHub.API/Controllers/PublishersController.cs
  PubHub/PubHub.API/Controllers/UsersController.cs
  PubHub/PubHub.API/Domain/Extensions/PubHubContextExtensions.cs
  PubHub/PubHub.API/ServiceExtensions.cs
  PubHub/PubHub.Common/Models/Accounts/AccountCreateModel.cs
  PubHub/PubHub.Common/Models/Accounts/UserCreatedResponseModel.cs
Labels: feature

#141 Fixed missing query in BookService
  PubHub/PubHub.Common/Extensions/GenericExtensions.cs
  PubHub/PubHub.Common/Services/BookService.cs
Labels: bug

#139 Fix Polly
  PubHub/PubHub.Common/Services/HttpClientService.cs
Labels: bug

#142 Login and Manage publisher layout
  PubHub/PubHub.AdminPortal/Components/Auth/CustomAuthStateProvider.cs
  PubHub/PubHub.AdminPortal/Components/Auth/Login.razor
  PubHub/PubHub.AdminPortal/Components/Layout/NavMenu.razor
  PubHub/PubHub.AdminPortal/Components/Models/AccountForm.cs
  PubHub/PubHub.AdminPortal/Components/Models/PublisherForm.cs
  PubHub/PubHub.AdminPortal/Components/Pages/ManagePublishers.razor
  PubHub/PubHub.AdminPortal/Components/Pages/Modals/Publisher/CreatePublisherModal.razor
  PubHub/PubHub.AdminPortal/Components/_Imports.razor
  PubHub/PubHub.AdminPortal/Program.cs
  PubHub/PubHub.AdminPortal/PubHub.AdminPortal.csproj
  PubHub/PubHub.Common/Extensions/GenericExtensions.cs
  PubHub/PubHub.Common/Services/IPublisherService.cs
  PubHub/PubHub.Common/Services/PublisherService.cs
Labels: feature

#145 Updated services
  PubHub/PubHub.API/Controllers/Problems/ValidationProblemSpecification.cs
  PubHub/PubHub.API/Program.cs
  PubHub/PubHub.AdminPortal/Components/Models/TestData.cs
  PubHub/PubHub.AdminPortal/Components/Pages/Books.razor
  PubHub/PubHub.AdminPortal/Components/Pages/Home.razor
  PubHub/PubHub.AdminPortal/Components/Pages/Modals/Book/CreateBookModal.razor
  PubHub/PubHub.AdminPortal/Components/Pages/Modals/Book/UpdateBookModal.razor
  PubHub/PubHub.AdminPortal/Components/_Imports.razor
  PubHub/PubHub.Common/PubHub.Common.csproj
  PubHub/PubHub.Common/Services/AuthenticationService.cs
  PubHub/PubHub.Common/Services/AuthorService.cs
  PubHub/PubHub.Common/Services/BookService.cs
  PubHub/PubHub.Common/Services/ContentTypeService.cs
  PubHub/PubHub.Common/Services/ErrorResponse.cs
  PubHub/PubHub.Common/Services/GenreService.cs
  PubHub/PubHub.Common/Services/IAuthenticationService.cs
  PubHub/PubHub.Common/Services/IAuthorService.cs
  PubHub/PubHub.Common/Services/IBookService.cs
  PubHub/PubHub.Common/Services/IContentTypeService.cs
  PubHub/PubHub.Common/Services/IGenreService.cs
  PubHub/PubHub.Common/Services/IPublisherService.cs
  PubHub/PubHub.Common/Services/IUserService.cs
  PubHub/PubHub.Common/Services/PublisherService.cs
  PubHub/PubHub.Common/Services/ServiceInstanceResult.cs
  PubHub/PubHub.Common/Services/ServiceResult{TResult}.cs
  PubHub/PubHub.Common/Services/UserService.cs
Labels: feature

#149 Use user/publisher/operator ID in sub claim
  PubHub/PubHub.API/Controllers/AuthController.cs
  PubHub/PubHub.API/Domain/Auth/AuthService.cs
Labels: feature

#150 Msm/book mobile/book info view
  PubHub/PubHub.BookMobile/App.xaml
  PubHub/PubHub.BookMobile/Extensions/ServiceExtensions.cs
  PubHub/PubHub.BookMobile/Models/BookListingViewModel.cs
  PubHub/PubHub.BookMobile/PubHub.BookMobile.csproj
  PubHub/PubHub.BookMobile/Resources/Styles/Styles.xaml
  PubHub/PubHub.BookMobile/ViewModels/BookInfoViewModel.cs
  PubHub/PubHub.BookMobile/Views/BookInfo.xaml
  PubHub/PubHub.BookMobile/Views/BookInfo.xaml.cs
  PubHub/PubHub.BookMobile/Views/Home.xaml
  PubHub/PubHub.BookMobile/Views/Home.xaml.cs
  PubHub/PubHub.BookMobile/Views/Library.xaml
  PubHub/PubHub.BookMobile/Views/Library.xaml.cs
Labels: feature

#151 Warning hot fix
  PubHub/PubHub.AdminPortal/Components/Auth/Login.razor
  PubHub/PubHub.AdminPortal/Components/Models/AccountForm.cs
  PubHub/PubHub.AdminPortal/Components/Pages/Modals/Book/CreateBookModal.razor
  PubHub/PubHub.AdminPortal/Components/Pages/Modals/Publisher/CreatePublisherModal.razor
  PubHub/PubHub.Common/PubHub.Common.csproj
  PubHub/PubHub.Common/Services/AuthenticationService.cs
  PubHub/PubHub.Common/Services/ErrorResponse.cs
Labels: bug

#155 Added publisher to book info view
  PubHub/PubHub.BookMobile/Views/BookInfo.xaml
Labels: feature

#156 Setup projects for unit testing
  PubHub/PubHub.API/Controllers/PublishersController.cs
  PubHub/PubHub.API/Domain/PubHubContext.cs
  PubHub/PubHub.API/PubHub.API.csproj
  PubHub/PubHub.Common/Services/PublisherService.cs
  PubHub/PubHub.sln
  Test/PubHub.API.UT/Controllers/ControllerTests.cs
  Test/PubHub.API.UT/Controllers/PublishersControllerTests.cs
  Test/PubHub.API.UT/Extensions/ContextExtensions.cs
  Test/PubHub.API.UT/Extensions/EntityExtensions.cs
  Test/PubHub.API.UT/GlobalUsings.cs
  Test/PubHub.API.UT/PubHub.API.UT.csproj
  Test/PubHub.API.UT/Utilities/ApiDataGeneratorFixture.cs
  Test/PubHub.API.UT/Utilities/DatabaseFixture.cs
  Test/PubHub.Common.UT/GlobalUsings.cs
  Test/PubHub.Common.UT/PubHub.Common.UT.csproj
  Test/PubHub.Common.UT/Services/PublisherServiceTests.cs
  Test/PubHub.Common.UT/Services/ServiceTests.cs
  Test/PubHub.TestUtils/DataGeneratorFixture.cs
  Test/PubHub.TestUtils/Extensions/CollectionExtensions.cs
  Test/PubHub.TestUtils/PubHub.TestUtils.csproj
Labels: setup

#161 Error responses fix
  PubHub/PubHub.AdminPortal/Components/Pages/Books.razor
  PubHub/PubHub.AdminPortal/Components/Pages/ManagePublishers.razor
  PubHub/PubHub.AdminPortal/Components/Pages/Modals/Book/CreateBookModal.razor
  PubHub/PubHub.AdminPortal/Components/Pages/Modals/Book/UpdateBookModal.razor
  PubHub/PubHub.Common/Services/AuthenticationService.cs
  PubHub/PubHub.Common/Services/AuthorService.cs
  PubHub/PubHub.Common/Services/BookService.cs
  PubHub/PubHub.Common/Services/ContentTypeService.cs
  PubHub/PubHub.Common/Services/GenreService.cs
  PubHub/PubHub.Common/Services/IAuthorService.cs
  PubHub/PubHub.Common/Services/IBookService.cs
  PubHub/PubHub.Common/Services/IContentTypeService.cs
  PubHub/PubHub.Common/Services/IGenreService.cs
  PubHub/PubHub.Common/Services/IPublisherService.cs
  PubHub/PubHub.Common/Services/IUserService.cs
  PubHub/PubHub.Common/Services/PublisherService.cs
  PubHub/PubHub.Common/Services/ServiceInstanceResult.cs
  PubHub/PubHub.Common/Services/ServiceResult.cs
  PubHub/PubHub.Common/Services/UserService.cs
Labels: bug

#165 Whitelist applications
  PubHub/PubHub.API/Controllers/AuthController.cs
  PubHub/PubHub.API/Controllers/AuthorsController.cs
  PubHub/PubHub.API/Controllers/BooksController.cs
  PubHub/PubHub.API/Controllers/ContentTypeController.cs
  PubHub/PubHub.API/Controllers/GenresController.cs
  PubHub/PubHub.API/Controllers/PublishersController.cs
  PubHub/PubHub.API/Controllers/UsersController.cs
  PubHub/PubHub.API/Domain/Auth/AppWhitelist.cs
  PubHub/PubHub.API/Domain/Auth/AuthOptions.cs
  PubHub/PubHub.API/Domain/Auth/AuthService.cs
  PubHub/PubHub.API/Domain/Auth/WhitelistOptions.cs
  PubHub/PubHub.API/Domain/Auth/WhitelistService.cs
  PubHub/PubHub.API/Program.cs
  PubHub/PubHub.API/ServiceExtensions.cs
  PubHub/PubHub.API/appsettings.json
  PubHub/PubHub.AdminPortal/Program.cs
  PubHub/PubHub.AdminPortal/appsettings.json
  PubHub/PubHub.BookMobile/MauiProgram.cs
  PubHub/PubHub.BookMobile/appsettings.json
  PubHub/PubHub.Common/ApiService/ApiConstants.cs
  PubHub/PubHub.Common/ApiService/ApiOptions.cs
  PubHub/PubHub.Common/Extensions/ServiceExtensions.cs
  PubHub/PubHub.Common/Services/HttpClientService.cs
  Test/PubHub.API.UT/Controllers/PublishersControllerTests.cs
  Test/PubHub.Common.UT/Services/PublisherServiceTests.cs
Labels: feature

#164 Input validation on the Admin portal
  PubHub/PubHub.AdminPortal/Components/Auth/Login.razor
  PubHub/PubHub.AdminPortal/Components/Constants/RegexConstants.cs
  PubHub/PubHub.AdminPortal/Components/Constants/ResponseCodeConstants.cs
  PubHub/PubHub.AdminPortal/Components/Models/AccountForm.cs
  PubHub/PubHub.AdminPortal/Components/Models/BookForm.cs
  PubHub/PubHub.AdminPortal/Components/Models/LoginForm.cs
  PubHub/PubHub.AdminPortal/Components/Models/PublisherForm.cs
  PubHub/PubHub.AdminPortal/Components/Pages/ManagePublishers.razor
  PubHub/PubHub.AdminPortal/Components/Pages/Modals/Book/CreateBookModal.razor
  PubHub/PubHub.AdminPortal/Components/Pages/Modals/Book/UpdateBookModal.razor
  PubHub/PubHub.AdminPortal/Components/Pages/Modals/Publisher/CreatePublisherModal.razor
  PubHub/PubHub.AdminPortal/Components/_Imports.razor
  PubHub/PubHub.Common/Services/IPublisherService.cs
  PubHub/PubHub.Common/Services/PublisherService.cs
Labels: feature

#169 Changes to Create book after input validation
  PubHub/PubHub.AdminPortal/Components/Pages/Modals/Book/CreateBookModal.razor
Labels: feature

#175 Fixed the "Closed Stream" issue in services
  PubHub/PubHub.BookMobile/App.xaml.cs
  PubHub/PubHub.Common/Services/AuthenticationService.cs
  PubHub/PubHub.Common/Services/AuthorService.cs
  PubHub/PubHub.Common/Services/BookService.cs
  PubHub/PubHub.Common/Services/ContentTypeService.cs
  PubHub/PubHub.Common/Services/GenreService.cs
  PubHub/PubHub.Common/Services/HttpClientService.cs
  PubHub/PubHub.Common/Services/IAuthenticationService.cs
  PubHub/PubHub.Common/Services/IAuthorService.cs
  PubHub/PubHub.Common/Services/IBookService.cs
  PubHub/PubHub.Common/Services/IContentTypeService.cs
  PubHub/PubHub.Common/Services/IGenreService.cs
  PubHub/PubHub.Common/Services/IHttpClientService.cs
  PubHub/PubHub.Common/Services/IPublisherService.cs
  PubHub/PubHub.Common/Services/PublisherService.cs
  PubHub/PubHub.Common/Services/UserService.cs
Labels: fix

#176 API restrictions
  PubHub/PubHub.API/Controllers/AuthController.cs
  PubHub/PubHub.API/Controllers/AuthorsController.cs
  PubHub/PubHub.API/Controllers/BooksController.cs
  PubHub/PubHub.API/Controllers/ContentTypeController.cs
  PubHub/PubHub.API/Controllers/GenresController.cs
  PubHub/PubHub.API/Controllers/Problems/ProblemResults.cs
  PubHub/PubHub.API/Controllers/PublishersController.cs
  PubHub/PubHub.API/Controllers/UsersController.cs
  PubHub/PubHub.API/Domain/Auth/AccessResult.cs
  PubHub/PubHub.API/Domain/Auth/AccessResultExtensions.cs
  PubHub/PubHub.API/Domain/Auth/AccessService.cs
  PubHub/PubHub.API/Domain/Auth/AppWhitelist.cs
  PubHub/PubHub.API/Domain/Auth/WhitelistService.cs
  PubHub/PubHub.API/Domain/Extensions/ClaimsExtensions.cs
  PubHub/PubHub.API/Domain/Services/TypeLookupService.cs
  PubHub/PubHub.API/ServiceExtensions.cs
  PubHub/PubHub.API/appsettings.json
  Test/PubHub.API.UT/Controllers/PublishersControllerTests.cs
Labels: feature

#181 Small changes to admin portal
  PubHub/PubHub.AdminPortal/Components/Auth/CustomAuthStateProvider.cs
  PubHub/PubHub.AdminPortal/Components/Auth/Login.razor
  PubHub/PubHub.AdminPortal/Components/Auth/SignInOrOut.razor
  PubHub/PubHub.AdminPortal/Components/Pages/Modals/Book/CreateBookModal.razor
  PubHub/PubHub.AdminPortal/Components/Pages/Modals/Book/RemoveBookModal.razor
  PubHub/PubHub.AdminPortal/Components/Pages/Modals/Publisher/CreatePublisherModal.razor
Labels: feature

#183 Lockout
  PubHub/PubHub.API/Controllers/AuthController.cs
  PubHub/PubHub.API/Domain/Auth/AccessResult.cs
  PubHub/PubHub.API/Domain/Auth/AccessService.cs
  PubHub/PubHub.API/Domain/Seeding/AccountSeed.cs
  PubHub/PubHub.API/Migrations/20240409192455_Seeding.cs
  PubHub/PubHub.API/ServiceExtensions.cs
  PubHub/PubHub.AdminPortal/Components/Auth/CustomAuthStateProvider.cs
  PubHub/PubHub.BookMobile/ViewModels/LibraryViewModel.cs
Labels: feature

#182 Mobile Profile View
  PubHub/PubHub.API/Controllers/UsersController.cs
  PubHub/PubHub.BookMobile/App.xaml.cs
  PubHub/PubHub.BookMobile/AppShell.xaml
  PubHub/PubHub.BookMobile/Auth/User.cs
  PubHub/PubHub.BookMobile/AuthorizedShell.xaml
  PubHub/PubHub.BookMobile/Extensions/HandlerExtensions.cs
  PubHub/PubHub.BookMobile/Extensions/ServiceExtensions.cs
  PubHub/PubHub.BookMobile/LoadingShell.xaml
  PubHub/PubHub.BookMobile/LoadingShell.xaml.cs
  PubHub/PubHub.BookMobile/MauiProgram.cs
  PubHub/PubHub.BookMobile/PubHub.BookMobile.csproj
  PubHub/PubHub.BookMobile/Resources/Styles/Styles.xaml
  PubHub/PubHub.BookMobile/Services/MauiHandlerService.cs
  PubHub/PubHub.BookMobile/ViewModels/LibraryViewModel.cs
  PubHub/PubHub.BookMobile/ViewModels/LoginViewModel.cs
  PubHub/PubHub.BookMobile/ViewModels/ProfileViewModel.cs
  PubHub/PubHub.BookMobile/Views/BookInfo.xaml
  PubHub/PubHub.BookMobile/Views/BookInfo.xaml.cs
  PubHub/PubHub.BookMobile/Views/Home.xaml
  PubHub/PubHub.BookMobile/Views/Home.xaml.cs
  PubHub/PubHub.BookMobile/Views/Library.xaml
  PubHub/PubHub.BookMobile/Views/Library.xaml.cs
  PubHub/PubHub.BookMobile/Views/LoadingView.xaml
  PubHub/PubHub.BookMobile/Views/LoadingView.xaml.cs
  PubHub/PubHub.BookMobile/Views/Login.xaml
  PubHub/PubHub.BookMobile/Views/Login.xaml.cs
  PubHub/PubHub.BookMobile/Views/Logout.xaml.cs
  PubHub/PubHub.BookMobile/Views/Profile.xaml
  PubHub/PubHub.BookMobile/Views/Profile.xaml.cs
  PubHub/PubHub.Common/ErrorsCodeConstants.cs
  PubHub/PubHub.Common/Models/Accounts/AccountUpdateModel.cs
  PubHub/PubHub.Common/Models/Users/UserUpdateModel.cs
Labels: feature

#185 Fix and improve access service and results
  PubHub/PubHub.API/Controllers/AuthController.cs
  PubHub/PubHub.API/Controllers/AuthorsController.cs
  PubHub/PubHub.API/Controllers/BooksController.cs
  PubHub/PubHub.API/Controllers/ContentTypeController.cs
  PubHub/PubHub.API/Controllers/GenresController.cs
  PubHub/PubHub.API/Controllers/PublishersController.cs
  PubHub/PubHub.API/Controllers/UsersController.cs
  PubHub/PubHub.API/Domain/Auth/AccessResult.cs
  PubHub/PubHub.API/Domain/Auth/AccessResultExtensions.cs
  PubHub/PubHub.API/Domain/Auth/AccessService.cs
Labels: bug

#186 Msm/registration
  PubHub/PubHub.BookMobile/Extensions/ServiceExtensions.cs
  PubHub/PubHub.BookMobile/PubHub.BookMobile.csproj
  PubHub/PubHub.BookMobile/ViewModels/RegisterViewModel.cs
  PubHub/PubHub.BookMobile/Views/Login.xaml
  PubHub/PubHub.BookMobile/Views/Logout.xaml
  PubHub/PubHub.BookMobile/Views/Profile.xaml
  PubHub/PubHub.BookMobile/Views/Register.xaml
  PubHub/PubHub.BookMobile/Views/Register.xaml.cs
Labels: feature, fix

#187 Added book summary to BookInfo View
  PubHub/PubHub.BookMobile/ViewModels/BookInfoViewModel.cs
  PubHub/PubHub.BookMobile/Views/BookInfo.xaml
  PubHub/PubHub.BookMobile/Views/BookInfo.xaml.cs
Labels: feature

#189 Purchase books
  PubHub/PubHub.API/Controllers/BooksController.cs
  PubHub/PubHub.API/Domain/Services/TypeLookupService.cs
  PubHub/PubHub.API/appsettings.json
  PubHub/PubHub.Common/AccessTypeConstants.cs
Labels: feature

#193 Enabling encryption on communication
  PubHub/PubHub.API/Program.cs
  PubHub/PubHub.AdminPortal/Program.cs
Labels: feature

#196 Buy Books
  PubHub/PubHub.API/Controllers/BooksController.cs
  PubHub/PubHub.BookMobile/ViewModels/BookInfoViewModel.cs
  PubHub/PubHub.BookMobile/ViewModels/LibraryViewModel.cs
  PubHub/PubHub.BookMobile/Views/BookInfo.xaml
  PubHub/PubHub.BookMobile/Views/BookInfo.xaml.cs
  PubHub/PubHub.Common/Services/BookService.cs
  PubHub/PubHub.Common/Services/IBookService.cs
Labels: feature, fix

#199 Replaced Preference storage with secure storage
  PubHub/PubHub.BookMobile/App.xaml.cs
  PubHub/PubHub.BookMobile/Auth/User.cs
  PubHub/PubHub.BookMobile/MauiProgram.cs
  PubHub/PubHub.BookMobile/ViewModels/LoginViewModel.cs
  PubHub/PubHub.BookMobile/ViewModels/RegisterViewModel.cs
  PubHub/PubHub.Common/Models/Accounts/AccountUpdateModel.cs
  PubHub/PubHub.Common/PubHub.Common.csproj
Labels: feature

#200 Added better exception handling
  PubHub/PubHub.BookMobile/Auth/User.cs
  PubHub/PubHub.BookMobile/Converters/IsAudiobookConverter.cs
  PubHub/PubHub.BookMobile/Converters/IsEbookConverter.cs
  PubHub/PubHub.BookMobile/ErrorSpecifications/BadRequestError.cs
  PubHub/PubHub.BookMobile/ErrorSpecifications/InvalidTokenError.cs
  PubHub/PubHub.BookMobile/ErrorSpecifications/NoConnectionError.cs
  PubHub/PubHub.BookMobile/ErrorSpecifications/NotFoundError.cs
  PubHub/PubHub.BookMobile/ErrorSpecifications/SetSecureStorageError.cs
  PubHub/PubHub.BookMobile/ErrorSpecifications/UnauthorizedError.cs
  PubHub/PubHub.BookMobile/ErrorSpecifications/UnproccessableEntityError.cs
  PubHub/PubHub.BookMobile/Extensions/ServiceExtensions.cs
  PubHub/PubHub.BookMobile/Models/BookListingViewModel.cs
  PubHub/PubHub.BookMobile/Models/PageInfo.cs
  PubHub/PubHub.BookMobile/StorageConstants.cs
  PubHub/PubHub.BookMobile/ViewModels/BookInfoViewModel.cs
  PubHub/PubHub.BookMobile/ViewModels/LibraryViewModel.cs
  PubHub/PubHub.BookMobile/ViewModels/LoginViewModel.cs
  PubHub/PubHub.BookMobile/ViewModels/NavigationObject.cs
  PubHub/PubHub.BookMobile/ViewModels/PersonalLibraryViewModel.cs
  PubHub/PubHub.BookMobile/ViewModels/ProfileViewModel.cs
  PubHub/PubHub.BookMobile/ViewModels/RegisterViewModel.cs
  PubHub/PubHub.BookMobile/Views/BookInfo.xaml.cs
  PubHub/PubHub.BookMobile/Views/Logout.xaml.cs
  PubHub/PubHub.Common/ErrorsCodeConstants.cs
Labels: feature

#201 EpubBook reader service
  PubHub/PubHub.AdminPortal/Components/Pages/Modals/Book/CreateBookModal.razor
  PubHub/PubHub.AdminPortal/Components/_Imports.razor
  PubHub/PubHub.AdminPortal/Program.cs
  PubHub/PubHub.Common/Extensions/ServiceExtensions.cs
  PubHub/PubHub.Common/Helpers/FileHandler.cs
  PubHub/PubHub.Common/PubHub.Common.csproj
  PubHub/PubHub.Common/Services/AuthenticationService.cs
  PubHub/PubHub.Common/Services/AuthorService.cs
  PubHub/PubHub.Common/Services/BookService.cs
  PubHub/PubHub.Common/Services/ContentTypeService.cs
  PubHub/PubHub.Common/Services/EpubReaderService.cs
  PubHub/PubHub.Common/Services/GenreService.cs
  PubHub/PubHub.Common/Services/HttpServiceResult.cs
  PubHub/PubHub.Common/Services/HttpServiceResult{TResult}.cs
  PubHub/PubHub.Common/Services/IAuthenticationService.cs
  PubHub/PubHub.Common/Services/IAuthorService.cs
  PubHub/PubHub.Common/Services/IBookService.cs
  PubHub/PubHub.Common/Services/IContentTypeService.cs
  PubHub/PubHub.Common/Services/IEpubReaderService.cs
  PubHub/PubHub.Common/Services/IGenreService.cs
  PubHub/PubHub.Common/Services/IPublisherService.cs
  PubHub/PubHub.Common/Services/IUserService.cs
  PubHub/PubHub.Common/Services/PublisherService.cs
  PubHub/PubHub.Common/Services/ServiceResult.cs
  PubHub/PubHub.Common/Services/ServiceResult{TResult}.cs
  PubHub/PubHub.Common/Services/UserService.cs
Labels: feature

#203 Quick fix
  PubHub/PubHub.Common/Services/BookService.cs
  PubHub/PubHub.Common/Services/IBookService.cs
Labels: feature

#204 Update polly retry policy
  PubHub/PubHub.API/Controllers/BooksController.cs
  PubHub/PubHub.Common/Extensions/ServiceExtensions.cs
  PubHub/PubHub.Common/ResilienceConstants.cs
  PubHub/PubHub.Common/Services/HttpClientService.cs
Labels: feature, fix

#205 Added validation
  PubHub/PubHub.BookMobile/ViewModels/LibraryViewModel.cs
  PubHub/PubHub.BookMobile/ViewModels/LoginViewModel.cs
  PubHub/PubHub.BookMobile/ViewModels/ProfileViewModel.cs
  PubHub/PubHub.BookMobile/ViewModels/RegisterViewModel.cs
  PubHub/PubHub.BookMobile/Views/Library.xaml
  PubHub/PubHub.BookMobile/Views/Login.xaml
  PubHub/PubHub.BookMobile/Views/Profile.xaml
  PubHub/PubHub.BookMobile/Views/Register.xaml
Labels: feature

#206 Terminate publishers
  PubHub/PubHub.AdminPortal/Components/Pages/ManagePublishers.razor
  PubHub/PubHub.AdminPortal/Components/Pages/Modals/Publisher/CreatePublisherModal.razor
  PubHub/PubHub.AdminPortal/Components/Pages/Modals/Publisher/RemovePublisherModal.razor
  PubHub/PubHub.AdminPortal/appsettings.json
Labels: feature

#208 Input validation
  PubHub/PubHub.AdminPortal/Components/Constants/ResponseCodeConstants.cs
  PubHub/PubHub.AdminPortal/Components/Models/AccountForm.cs
  PubHub/PubHub.AdminPortal/Components/Models/BookForm.cs
  PubHub/PubHub.AdminPortal/Components/Models/LoginForm.cs
  PubHub/PubHub.AdminPortal/Components/Models/PublisherForm.cs
  PubHub/PubHub.AdminPortal/Components/Pages/Modals/Book/CreateBookModal.razor
  PubHub/PubHub.AdminPortal/Components/Pages/Modals/Book/RemoveBookModal.razor
  PubHub/PubHub.AdminPortal/Components/Pages/Modals/Book/UpdateBookModal.razor
  PubHub/PubHub.AdminPortal/Components/Pages/Modals/Publisher/CreatePublisherModal.razor
  PubHub/PubHub.AdminPortal/Components/Pages/Modals/Publisher/RemovePublisherModal.razor
  PubHub/PubHub.AdminPortal/Components/_Imports.razor
  PubHub/PubHub.BookMobile/Auth/User.cs
  PubHub/PubHub.BookMobile/ViewModels/BookInfoViewModel.cs
  PubHub/PubHub.BookMobile/ViewModels/LibraryViewModel.cs
  PubHub/PubHub.BookMobile/ViewModels/LoginViewModel.cs
  PubHub/PubHub.BookMobile/ViewModels/PersonalLibraryViewModel.cs
  PubHub/PubHub.BookMobile/ViewModels/ProfileViewModel.cs
  PubHub/PubHub.BookMobile/ViewModels/RegisterViewModel.cs
  PubHub/PubHub.BookMobile/Views/BookInfo.xaml.cs
  PubHub/PubHub.Common/ErrorSpecifications/BadRequestError.cs
  PubHub/PubHub.Common/ErrorSpecifications/ConflictError.cs
  PubHub/PubHub.Common/ErrorSpecifications/InvalidTokenError.cs
  PubHub/PubHub.Common/ErrorSpecifications/NoConnectionError.cs
  PubHub/PubHub.Common/ErrorSpecifications/NotFoundError.cs
  PubHub/PubHub.Common/ErrorSpecifications/SetSecureStorageError.cs
  PubHub/PubHub.Common/ErrorSpecifications/UnauthorizedError.cs
  PubHub/PubHub.Common/ErrorSpecifications/UnproccessableEntityError.cs
  PubHub/PubHub.Common/ErrorsCodeConstants.cs
  PubHub/PubHub.Common/ValidationAnnotationConstants.cs
Labels: feature

#212 Jbn/api rate limiting
  PubHub/PubHub.API/Controllers/AuthController.cs
  PubHub/PubHub.API/Controllers/AuthorsController.cs
  PubHub/PubHub.API/Controllers/BooksController.cs
  PubHub/PubHub.API/Controllers/ContentTypeController.cs
  PubHub/PubHub.API/Controllers/GenresController.cs
  PubHub/PubHub.API/Controllers/PublishersController.cs
  PubHub/PubHub.API/Controllers/UsersController.cs
  PubHub/PubHub.API/Program.cs
  PubHub/PubHub.AdminPortal/Components/Pages/Books.razor
  PubHub/PubHub.AdminPortal/appsettings.json
  PubHub/PubHub.Common/ErrorSpecifications/TooManyRequestError.cs
  PubHub/PubHub.Common/ErrorsCodeConstants.cs
  PubHub/PubHub.Common/Services/AuthenticationService.cs
  PubHub/PubHub.Common/Services/AuthorService.cs
  PubHub/PubHub.Common/Services/BookService.cs
  PubHub/PubHub.Common/Services/ContentTypeService.cs
  PubHub/PubHub.Common/Services/EpubReaderService.cs
  PubHub/PubHub.Common/Services/GenreService.cs
  PubHub/PubHub.Common/Services/IEpubReaderService.cs
  PubHub/PubHub.Common/Services/PublisherService.cs
  PubHub/PubHub.Common/Services/UserService.cs
Labels: feature

#215 Add rate limiter to Polly pipeline
  PubHub/PubHub.Common/Extensions/ServiceExtensions.cs
  PubHub/PubHub.Common/PubHub.Common.csproj
  PubHub/PubHub.Common/Services/HttpClientService.cs
Labels: feature

#217 Updating README
  README.md
Labels: documentation

#219 Endpoint for updating book progress
  PubHub/PubHub.API/Controllers/UsersController.cs
  PubHub/PubHub.API/appsettings.json
  PubHub/PubHub.Common/Models/Users/UserBookInfoModel.cs
  PubHub/PubHub.Common/Models/Users/UserBookUpdateModel.cs
Labels: feature

#220 Book progress can now be persisted on E-Book view
  PubHub/PubHub.BookMobile/Auth/User.cs
  PubHub/PubHub.BookMobile/ViewModels/BookContentInfoViewModel.cs
  PubHub/PubHub.BookMobile/ViewModels/BookInfoViewModel.cs
  PubHub/PubHub.BookMobile/ViewModels/EBookViewModel.cs
  PubHub/PubHub.BookMobile/Views/EBookView.xaml.cs
  PubHub/PubHub.Common/Services/IUserService.cs
  PubHub/PubHub.Common/Services/UserService.cs
Labels: feature, fix

#223 Added audio view
  PubHub/PubHub.API/Controllers/BooksController.cs
  PubHub/PubHub.API/appsettings.json
  PubHub/PubHub.BookMobile/Extensions/ServiceExtensions.cs
  PubHub/PubHub.BookMobile/MauiProgram.cs
  PubHub/PubHub.BookMobile/Platforms/Android/MainActivity.cs
  PubHub/PubHub.BookMobile/PubHub.BookMobile.csproj
  PubHub/PubHub.BookMobile/Resources/Fonts/icofont.ttf
  PubHub/PubHub.BookMobile/Resources/Styles/Icons.xaml
  PubHub/PubHub.BookMobile/ViewModels/AudiobookViewModel.cs
  PubHub/PubHub.BookMobile/ViewModels/BookContentInfoViewModel.cs
  PubHub/PubHub.BookMobile/Views/AudiobookView.xaml
  PubHub/PubHub.BookMobile/Views/AudiobookView.xaml.cs
  PubHub/PubHub.Common/Services/BookService.cs
  PubHub/PubHub.Common/Services/HttpClientService.cs
  PubHub/PubHub.Common/Services/IBookService.cs
  PubHub/PubHub.Common/Services/IHttpClientService.cs
Labels: feature

#228 Refresh tokens
  PubHub/PubHub.AdminPortal/Program.cs
  PubHub/PubHub.BookMobile/MauiProgram.cs
  PubHub/PubHub.BookMobile/PubHub.BookMobile.csproj
  PubHub/PubHub.Common/ApiService/ApiOptions.cs
  PubHub/PubHub.Common/ApiService/ServiceRoot.cs
  PubHub/PubHub.Common/Extensions/ServiceExtensions.cs
  PubHub/PubHub.Common/PubHub.Common.csproj
  PubHub/PubHub.Common/Services/AuthenticationService.cs
  PubHub/PubHub.Common/Services/AuthorService.cs
  PubHub/PubHub.Common/Services/BookService.cs
  PubHub/PubHub.Common/Services/ContentTypeService.cs
  PubHub/PubHub.Common/Services/GenreService.cs
  PubHub/PubHub.Common/Services/HttpClientService.cs
  PubHub/PubHub.Common/Services/IHttpClientService.cs
  PubHub/PubHub.Common/Services/PublisherService.cs
  PubHub/PubHub.Common/Services/UserService.cs
  Test/PubHub.Common.UT/Services/PublisherServiceTests.cs
Labels: fix

#231 Polly feedback
  PubHub/PubHub.AdminPortal/Components/Pages/Modals/Book/CreateBookModal.razor
  PubHub/PubHub.AdminPortal/Components/Pages/Shared/PollyInfo.razor
  PubHub/PubHub.Common/Extensions/ServiceExtensions.cs
  PubHub/PubHub.Common/ResilienceConstants.cs
  PubHub/PubHub.Common/Services/HttpClientService.cs
  PubHub/PubHub.Common/Services/PollyInfoService.cs
Labels: feature, fix

#230 Msm/better rate limiting
  PubHub/PubHub.API/Controllers/AuthController.cs
  PubHub/PubHub.API/Controllers/AuthorsController.cs
  PubHub/PubHub.API/Controllers/BooksController.cs
  PubHub/PubHub.API/Controllers/ContentTypeController.cs
  PubHub/PubHub.API/Controllers/GenresController.cs
  PubHub/PubHub.API/Controllers/PublishersController.cs
  PubHub/PubHub.API/Controllers/UsersController.cs
  PubHub/PubHub.API/Program.cs
  Test/PubHub.API.FT/LoadTests.cs
  Test/PubHub.API.FT/Utilities/ApiFixture.cs
Labels: feature, fix

#229 Msm/mobile refresh token
  PubHub/PubHub.BookMobile/App.xaml.cs
  PubHub/PubHub.BookMobile/Auth/User.cs
  PubHub/PubHub.BookMobile/ViewModels/AudiobookViewModel.cs
  PubHub/PubHub.BookMobile/ViewModels/BookInfoViewModel.cs
  PubHub/PubHub.BookMobile/Views/AudiobookView.xaml
  PubHub/PubHub.BookMobile/Views/BookContentInfo.xaml.cs
  PubHub/PubHub.BookMobile/Views/Home.xaml.cs
  PubHub/PubHub.BookMobile/appsettings.json
  PubHub/PubHub.Common/Services/AuthenticationService.cs
Labels: feature, fix

#234 Added polly and too many requests
  PubHub/PubHub.AdminPortal/Components/Auth/Login.razor
  PubHub/PubHub.AdminPortal/Components/Pages/ManagePublishers.razor
  PubHub/PubHub.AdminPortal/Components/Pages/Modals/Book/RemoveBookModal.razor
  PubHub/PubHub.AdminPortal/Components/Pages/Modals/Publisher/RemovePublisherModal.razor
Labels: fix
